language: objective-c

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="ReSwift-Thunk"

matrix:
  include:
    - osx_image: xcode9.3
      env: SCHEME="macOS"  SDK="macosx10.13"          DESTINATION="arch=x86_64"                    SWIFT_VERSION="4.1" ACTION="test"
    - osx_image: xcode10.1
      env: SCHEME="macOS"  SDK="macosx10.14"          DESTINATION="arch=x86_64"                    SWIFT_VERSION="4.2" ACTION="test"
    - osx_image: xcode10.2
      env: SCHEME="macOS"  SDK="macosx10.14"          DESTINATION="arch=x86_64"                    SWIFT_VERSION="5.0" ACTION="test" POD_LINT="YES"
    - osx_image: xcode10.2
      env: SCHEME="iOS"    SDK="iphonesimulator"      DESTINATION="OS=12.0,name=iPhone 8"          SWIFT_VERSION="5.0" ACTION="test"
    - osx_image: xcode10.2
      env: SCHEME="tvOS"   SDK="appletvsimulator"     DESTINATION="OS=12.0,name=Apple TV 4K"       SWIFT_VERSION="5.0" ACTION="test"
    - osx_image: xcode10.2
      env: SCHEME="watchOS"  SDK="watchsimulator"     DESTINATION="OS=4.0,name=Apple Watch - 42mm" SWIFT_VERSION="5.0" ACTION="build"

before_install:
  - if [ $POD_LINT == "YES" ]; then
      gem install cocoapods -v '1.7.5';
      pod repo update;
    fi
  - carthage bootstrap --platform "$SCHEME" --verbose

install:
  - gem install xcpretty

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    "$ACTION"
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    SWIFT_VERSION=$SWIFT_VERSION
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --verbose;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J ReSwift-Thunk
